/*
 * File: app/model/ProfitLoss.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dashboard.model.ProfitLoss', {
    extend: 'Ext.data.Model',
    alias: 'model.profitloss',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'account'
        },
        {
            name: 'q1_2010'
        },
        {
            name: 'q2_2010'
        },
        {
            name: 'q3_2010'
        },
        {
            name: 'q4_2010'
        },
        {
            name: 'q1_2011'
        },
        {
            name: 'q2_2011'
        },
        {
            name: 'q3_2011'
        },
        {
            name: 'q4_2011'
        },
        {
            name: 'q1_2012'
        },
        {
            name: 'q2_2012'
        },
        {
            name: 'region'
        }
    ]
});